site_name: Wiki Pot
site_url: https://blog.arkj.org
repo_url: https://github.com/ark-j/wiki
repo_name: ark-j/wiki
theme:
  logo: assets/images/icon.jpg
  favicon: assets/images/icon.jpg
  name: material
  custom_dir: overrides
  palette:
    # -- colors setting --
    # palettle for light mode
    - scheme: default
      primary: indigo
      toggle:
        icon: material/weather-night
        name: switch to dark mode

    # palettle for dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/weather-sunny
        name: switch to light mode

  # -- font settings --
  font:
    code: JetBrainsMono Nerd Font

  # -- language settings --
  language: en

  # -- features --
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    # - content.tabs.link
    - content.tooltips
    - header.autohide
    - announce.dismiss
    - search.highlight
    - search.share
    - search.suggest
    # -- navigation specific
    - navigation.instant
    - navigation.instant.progress
    - navigation.footer
    - navigation.tabs
    - navigation.top
    - toc.follow

  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

extra_css:
  - css/termynal.css
  - css/custom.css

extra_javascript:
  - js/termynal.js
  - js/custom.js

plugins:
  - offline
  - tags
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: true
      background: white
      shadow: true
      manual: false

markdown_extensions:
  - markdown.extensions.toc:
      slugify:
        !!python/object/apply:pymdownx.slugs.slugify { kwds: { case: lower } }
      permalink: "🔗"
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path:
        - "codes"
      check_paths: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tabbed:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - sane_lists
  - md_in_html
  - admonition
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
nav:
  - index.md
  # - Mkdocs Guide:
  #     - guides/mkdocs/index.md
  - Guides:
      - Golang:
          - Tutorials:
              - guides/golang/tutorial/basics.md
              - guides/golang/tutorial/advanced.md
          - guides/golang/common-pitfalls.md
          - guides/golang/http-error-handler.md
      - Kubernetes:
          - guides/kubernetes/getting-started.md
          - guides/kubernetes/using-kubectl.md
          - guides/kubernetes/k3s-setup.md
      - Git:
          - guides/git/setting-up.md
      - Linux:
          - guides/linux/awesome-commands.md
          - guides/linux/file-permissions.md
          - guides/linux/virtual-machine.md
      - Neovim:
          - guides/neovim/config.md
  - Blog:
      - blog/openapi-golang.md
      - blog/golang-router.md
      - blog/opi5-ultra-setup.md
