[project]
nav = [
	{ "Home" = "index.md" },
	{ "Guides" = [
		{ "Golang" = [
			{ "Tutorials" = [
				"guides/golang/tutorial/basics.md",
				"guides/golang/tutorial/advanced.md",
			] },
			"guides/golang/common-pitfalls.md",
			"guides/golang/http-error-handler.md",
		] },
		{ "Kubernetes" = [
			"guides/kubernetes/getting-started.md",
			"guides/kubernetes/using-kubectl.md",
			"guides/kubernetes/k3s-setup.md",
		] },
		{ "Git" = [
			"guides/git/setting-up.md",
		] },
		{ "Linux" = [
			"guides/linux/awesome-commands.md",
			"guides/linux/file-permissions.md",
			"guides/linux/virtual-machine.md",
			"guides/linux/settingup-remote-store.md",
			"guides/linux/shell-scripting.md",
		] },
		{ "Neovim" = [
			"guides/neovim/config.md",
		] },
	] },
	{ "Syntax Guide" = "guides/mkdocs/index.md" },
	{ "Blog" = [
		"blog/openapi-golang.md",
		"blog/golang-router.md",
		"blog/opi5-ultra-setup.md",
	] },
]

# site settings
site_name = "wiki"
site_url = "https://wiki.jshk.dev"
site_author = "Jayesh Kale"
repo_url = "https://github.com/jshk00/wiki"
repo_name = "jshk00/wiki"
docs_dir = "docs"
extra_css = ["css/style.css", "css/termynal.css"]
extra_javascript = ["js/termynal.js", "js/custom.js"]

# extension
[project.markdown_extensions]
pymdownx.details = {}
pymdownx.caret = {}
pymdownx.mark = {}
pymdownx.tilde = {}
pymdownx.blocks.caption = {}
pymdownx.inlinehilite = {}
pymdownx.superfences = {}
pymdownx.keys = {}
attr_list = {}
admonition = {}
def_list = {}
md_in_html = {}
tables = {}
toc.permalink = true
toc.slugify.object = "pymdownx.slugs.slugify"
toc.slugify.kwds = { case = "lower" }
pymdownx.emoji.emoji_index = "zensical.extensions.emoji.twemoji"
pymdownx.emoji.emoji_generator = "zensical.extensions.emoji.to_svg"

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
linenums = false
linenums_style = "pymdownx-inline"
line_spans = "__span"
pygments_lang_class = true

[project.markdown_extensions.pymdownx.snippets]
base_path = "codes"

[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true

[project.markdown_extensions.pymdownx.tabbed.slugify]
object = "pymdownx.slugs.slugify"

[project.theme]
logo = "assets/images/icon.jpg"
favicon = "assets/images/icon.jpg"
custom_dirs = "overrides"
features = [
	"navigation.instant",
	"navigation.instant.prefetch",
	"navigation.instant.progress",
	"navigation.tracking",
	"navigation.tabs",
	"navigation.path",
	"navigation.prune",
	"toc.follow",
	"navigation.top",
	"search.highlight",
	"content.code.copy",
	"content.code.select",
]

[project.theme.font]
text = "Adwaita Sans"
code = "JetBrainsMono Nerd Font"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"
accent = "cyan"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"
accent = "cyan"
