# site settings
site_name = "wiki"
site_url = "https://wiki.jshk.dev"
site_author = "Jayesh Kale"
repo_url = "https://github.com/jshk00/wiki"
repo_name = "jshk00/wiki"
docs_dir = "docs"
extra_css = ["css/style.css", "css/termynal.css"]
extra_javascript = ["js/termynal.js", "js/custom.js"]

# nav tree
nav = [
	{ "Home" = "index.html" },
	{ "Guides" = [
		{ "Golang" = [
			{ "Tutorials" = [
				"guides/golang/tutorial/basics.md",
				"guides/golang/tutorial/advanced.md",
			] },
			"guides/golang/common-pitfalls.md",
			"guides/golang/http-error-handler.md",
		] },
		{ "Kubernetes" = [
			"guides/kubernetes/getting-started.md",
			"guides/kubernetes/using-kubectl.md",
			"guides/kubernetes/k3s-setup.md",
		] },
		{ "Git" = [
			"guides/git/setting-up.md",
		] },
		{ "Linux" = [
			"guides/linux/awesome-commands.md",
			"guides/linux/file-permissions.md",
			"guides/linux/virtual-machine.md",
			"guides/linux/settingup-remote-store.md",
			"guides/linux/shell-scripting.md",
			"guides/linux/ssh.md",
			"guides/linux/dns.md",
			"guides/linux/networking.md",
		] },
		{ "Neovim" = [
			"guides/neovim/config.md",
		] },
	] },
	# { "Syntax Guide" = "guides/mkdocs/index.md" },
	{ "Blog" = [
		"blog/openapi-golang.md",
		"blog/golang-router.md",
		"blog/opi5-ultra-setup.md",
	] },
]


[markdown_extensions]
attr_list = {}
admonition = {}
def_list = {}
md_in_html = {}
tables = {}
zensical.extensions.glightbox = {}

[markdown_extensions.toc]
permalink = true
slugify.object = "pymdownx.slugs.slugify"
slugify.kwds = { case = "lower" }

[markdown_extensions.pymdownx]
details = {}
caret = {}
mark = {}
tilde = {}
blocks.caption = {}
inlinehilite = {}
superfences = {}
keys = {}
emoji.emoji_index = "zensical.extensions.emoji.twemoji"
emoji.emoji_generator = "zensical.extensions.emoji.to_svg"

# highlight
highlight.anchor_linenums = true
highlight.linenums_style = "pymdownx-inline"
highlight.line_spans = "__span"
highlight.pygments_lang_class = true

# snippet
snippets.base_path = "codes"

# tabbed
tabbed.alternate_style = true
tabbed.slugify.object = "pymdownx.slugs.slugify"

[theme.icon.admonition]
note = "octicons/tag-16"
abstract = "octicons/checklist-16"
info = "octicons/info-16"
success = "octicons/check-16"
question = "octicons/question-16"
warning = "octicons/alert-16"
failure = "octicons/x-circle-16"
danger = "octicons/zap-16"
bug = "octicons/bug-16"
quote = "octicons/quote-16"


[theme]
logo = "assets/images/icon.jpg"
favicon = "assets/images/icon.jpg"
features = [
	"navigation.instant",
	"navigation.instant.progress",
	"navigation.tracking",
	"navigation.tabs",
	"navigation.path",
	"navigation.prune",
	"toc.follow",
	"navigation.top",
	"search.highlight",
	"content.code.copy",
]
# fonts
font.text = "Inter"
font.code = "JetBrainsMono Nerd Font"

[[theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"
accent = "cyan"

[[theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"
accent = "cyan"
