name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/configure-pages@v5
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install zensical
      - run: zensical build --clean
      - uses: actions/upload-pages-artifact@v4
        with:
          path: site
      - uses: actions/deploy-pages@v4
        id: deployment
      - run: |
          # Switch to the gh-pages branch
          git fetch origin gh-pages
          git checkout gh-pages
          # create cname file with content
          echo "wiki.jshk.dev" > CNAME
          # Add and commit the CNAME file
          git add CNAME
          git commit -m "(add) cname file"
          git push origin gh-pages
